### ISSUE TITLE
timeout exception

### ISSUE THREAD

**Issue by KleinXin** [PGijsbers/gama#107]
I have 96k features whose dimention is 270 to fit. When I try to fit those features by following the classification examples, it reported a timeout exception as shown in the image below.

![image](https://user-images.githubusercontent.com/13084622/93838781-7cbcfc00-fcbd-11ea-950a-45e6ec0f2ba6.png)

**Comment by PGijsbers** [comment]
Thanks for reporting this issue! Two quick questions:

1. Is it possible to share the data? (So I can reproduce the error locally)
2. Did this error prevent GAMA from building a model (e.g. could you still call `predict`  successfully despite this error)?
3. I suspect there may have been more output after this error, was that the case? If so, could you report the full output?

**Comment by PGijsbers** [comment]
Closing this issue because it's stale. @KleinXin if you do have information you can share, I'll still gladly look into it 👍 just leave a comment on this issue.
