### ISSUE TITLE
Import warnings

### ISSUE THREAD

**Issue by joaquinvanschoren** [PGijsbers/gama#20]
On import, a lot of warnings are thrown:

```
anaconda3/lib/python3.6/site-packages/deap/tools/_hypervolume/pyhv.py:33: ImportWarning: Falling back to the python version of hypervolume module. Expect this to be very slow.
  "module. Expect this to be very slow.", ImportWarning)
anaconda3/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
```

Is there something we can do about this? Is this specific to my anaconda setup?
Especially the first warning doesn't look so good.

**Comment by PGijsbers** [comment]
Thank you for the notice. I don't personally get the message on a fresh Ubuntu install. Looks like I should enforce DEAP >= 1.2.1 as per [deap#240](https://github.com/DEAP/deap/issues/240). Can you verify that your current DEAP version is 1.2.0 and that the error is not there after updating to v1.2.1?

**Comment by joaquinvanschoren** [comment]
I'm running deap 1.2.2
```
macwin029:gama joa$ pip show deap
Name: deap
Version: 1.2.2
Summary: Distributed Evolutionary Algorithms in Python
Home-page: https://www.github.com/deap
Author: deap Development Team
Author-email: deap-users@googlegroups.com
License: LGPL
Location: /Users/joa/anaconda3/lib/python3.6/site-packages
Requires:
Required-by: gama, TPOT
```

**Comment by joaquinvanschoren** [comment]
Ok. When do you expect `genetic_programming` to be merged?

**Comment by PGijsbers** [comment]
A week or two. While it does not change the way gama works, the back-end changes are substantial so I do want to run additional tests to make sure it did not break anything or degrades performance.

**Comment by PGijsbers** [comment]
merged. DEAP is no longer a dependency.
