### ISSUE TITLE
Runtime warning

### ISSUE THREAD

**Issue by joaquinvanschoren** [PGijsbers/gama#21]
I'm getting a lot of runtime warnings on the minimal example:
```
X, y = load_digits(return_X_y=True)
X_train, X_test, y_train, y_test= train_test_split(X, y, stratify=y, random_state=42)
automl = GamaClassifier(max_total_time=300, n_jobs=4)
automl.fit(X_train, y_train)
predictions = automl.predict(X_test)
print('accuracy', accuracy_score(y_test, predictions))
```

```
anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
Could not create a new individual from 50 iterations of mate_new
anaconda3/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
Could not create a new individual from 50 iterations of mate_new
Could not create a new individual from 50 iterations of mate_new
Could not create a new individual from 50 iterations of mate_new
```

The DeprecationWarning can be fixed easily, I assume? The second I'm not so sure about.

'Could not create a new individual' is not very descriptive. Does this mean that there is something wrong with the algorithm? Is there something the user should do (e.g. use different hyperparameters)?

**Comment by PGijsbers** [comment]
Thanks for reporting these issues. 
* The DeprecationWarning should be easily fixed. 
* 'Could not create new individual' was not meant to be printed at the default verbosity level. It is not something a user should fix. It is basically to say that it tried to create a new individual out of two existing individuals through mating/crossover 50 times, but could not create one that was not evaluated before. I will change the default output behavior, and improvements to mating behavior are already worked on in the genetic_programming branch.

**Comment by joaquinvanschoren** [comment]
OK, cool. 

Maybe also change the message to something like 'Notice: Gave up on mating X and Y. Could not create a new individual that was not evaluated before after 50 iterations'?

**Comment by PGijsbers** [comment]
Closing this issue because the DeprecationWarning is fixed (by upgrading minimum version of scikit-learn and using the new SimpleImputer) and the error message has a separate issue.
