### ISSUE TITLE
score function

### ISSUE THREAD

**Issue by joaquinvanschoren** [PGijsbers/gama#22]
Adding a score() function would make gama more of a drop-in replacement for scikit-learn classifiers in scripts.

**Comment by PGijsbers** [comment]
Agreed, but there is a reason it is not included right now.
I don't generally like how scikit-learn's score function always returns accuracy for classification and R2 for regression. I think it makes more sense to report the metric that is optimized towards. However, that would make its behaviour different from scikit-learn. What do you think?

**Comment by joaquinvanschoren** [comment]
I think that adding a score function makes things easier overall. 
People who use gama standalone probably know that they are getting log_loss. 
If people want to do comparisons on accuracy they should be smart enough to set the objective to accuracy?

**Comment by PGijsbers** [comment]
Sounds fine :)

Conclusion: add a score function which reports the score of the metric that was optimized towards.

**Comment by PGijsbers** [comment]
Done 6f450ae3fd43aa6e286212cae46d8bc7c226b9b9
