### ISSUE TITLE
Allow CSV files

### ISSUE THREAD

**Issue by PGijsbers** [PGijsbers/gama#66]
Despite the limitations of CSV files (in particular no feature type annotation), I think we should support a best-effort try for working with CSV files. In the future this can integrate with the Dashboard tool to annotate the csv/convert it to arff for a more robust experience.

**Comment by GaganaB** [comment]
Hi just wanted to check... any updates on csv support with gama? Can I convert files to arff and work? Thanks.

**Comment by PGijsbers** [comment]
No updates right now. I hope to get some basic support soon.
In the mean time, you can convert your csv to arff using [weka](https://stackoverflow.com/questions/10341701/convert-csv-to-arff-using-weka), [this script I wrote](https://github.com/openml/ARFF-tools/blob/master/csv-to-arff.py) (maybe not very user friendly) , an online conversion tool (they exist but I have no experience with them), or manually.

**Comment by PGijsbers** [comment]
You can also use pandas to read the csv file.

**Comment by GaganaB** [comment]
@PGijsbers  thank you so much! Will look out for newer features.
