### ISSUE TITLE
Variables type definition

### ISSUE THREAD

**Issue by iXanthos** [PGijsbers/gama#91]
Hello, I am reading the docs and I came across this:

`This means that GAMA might use a wrong feature transformation for the data (e.g. one-hot encoding on a numeric feature or scaling on a categorical feature). Note that this is not unique to GAMA, but any framework which accepts numeric input without meta-data.`

I know arff is a format encapsulating the data types in its structure, but me, and many others, use .csv data files, hence we do not provide the data types information in our original data. My question is: If my data are in .csv format and I use pandas, is there a way to ensure there will be no mistakes when inferring the data types? And also, is there a way to manually define the data types?

Thank you

**Comment by PGijsbers** [comment]
> If my data are in .csv format and I use pandas, is there a way to ensure there will be no mistakes when inferring the data types?

In general, no. If you are aware of a technique that ensures no mistakes are made with data type inference, please let me know, I am not familiar. When presented with a numpy array GAMA will use some heuristics to determine which feature is categorical, and which is numerical. If presented with a dataframe, GAMA will assume the user correctly set the dtypes of the dataframe, which brings us to:

> And also, is there a way to manually define the data types?

If you load the data from csv into a pandas DataFrame, you can set the `dtype` of the series in the DataFrame. In particular, use `dtype='category'` for categorical features, then GAMA will use this information. From the top of my head, it should read something like:

```python
df = pd.DataFrame.read_csv("mydata.csv")
df["my_categorical"] = df["my_categorical"].astype(dtype='category')
```

**Comment by iXanthos** [comment]
> In general, no. If you are aware of a technique that ensures no mistakes are made with data type inference, please let me know, I am not familiar.
This is debatable and no, I havent seen a tool or something else that can do it 100% robustly.

> If you load the data from csv into a pandas DataFrame, you can set the `dtype` of the series in the DataFrame. In particular, use `dtype='category'` for categorical features, then GAMA will use this information.
yeah I am aware of that pandas functionality. Didnt realize gama uses it, but thanks, I will pass the variables types through the df.
